create table member
(
    member_id          bigint generated by default as identity,
    username           varchar(255) unique,
    password           varchar(255),
    name               varchar(255),
    phone              varchar(255),
    email              varchar(255),
    position           varchar(255),
    department         varchar(255),
    role               varchar(255),
    avatar             varchar(255),
    created_date       timestamp,
    last_modified_date timestamp,
    created_by         varchar(255),
    last_modified_by   varchar(255),
    primary key (member_id)
);

create table refresh_token
(
    key         varchar(255) not null,
    value       varchar(255),
    expiry_date timestamp,
    primary key (key)
);